[package]
name = "Splite_text"
version = "0.1.0"
edition = "2024"

[dependencies]
file_spliter = { path = "file_spliter" }
yt_subtitle_download = { path = "yt_subtitle_download" }
serde = { version = "1.0", features = ["derive"] }
